services:
  app:
    build: ./FlaskApp
    depends_on:
      - db
    ports:
      - "5002:5002"

  db:
    build: ./db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
